server:
  port: 40040

spring:
  datasource:
    url: jdbc:mysql://47.119.164.128:3306/witty_waves?useSSL=false&serverTimezone=UTC
    username: xxxx
    password: xxxx
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.witty.entity

# 日志配置
logging:
  level:
    com:
      witty: debug


app:
  name: Witty Waves
  reecho:
    token: xxxx
    generate-url: https://www.xxx.cn

