server:
  port: 40040

spring:
  datasource:
    url: jdbc:mysql://47.119.164.128:3306/witty_waves?useSSL=false&serverTimezone=UTC
    username: huanglin
    password: huanglin2024@MySQL
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.witty.entity

# 日志配置
logging:
  level:
    com:
      witty: debug


app:
  name: Witty Waves
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0bgf888d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    expiration: 3600
  reecho:
    token: sk-78cb6c09907b6156e2d68acc90b26d6c
    generate-url: https://v1.reecho.cn/api/tts/simple-generate


